treewide: Standardize usage of timer_delete_sync
This reverts commit e757b33.

Greg REALLY mucked this all up trying to protect the ABI. Luckily,
that is of no concern to us.

Subsequent to e259124 ("timers: Get rid of del_singleshot_timer_sync()"),
this resolves the following compilation errors:

../kernel/irq/sbalance.c:374:9: error: implicit declaration of function 'del_singleshot_timer_sync' [-Wimplicit-function-declaration]
  374 |         del_singleshot_timer_sync(&timer.timer);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>