tensor_aio: Add missing ARM_PMUV3 include
Subsequent to 278e973f01d6f82dcdcef6e48430d3c68777d4be ("UPSTREAM: arm64: perf: Move PMUv3 driver to
drivers/perf"), this resolves the following compilation errors:

../drivers/devfreq/tensor_aio.c:190:24: error: 'ARMV8_PMUV3_PERFCTR_CPU_CYCLES' undeclared here (not in a function)
  190 |         [CPU_CYCLES] = ARMV8_PMUV3_PERFCTR_CPU_CYCLES,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/devfreq/tensor_aio.c:191:31: error: 'ARMV8_AMU_PERFCTR_STALL_BACKEND_MEM' undeclared here (not in a function)
  191 |         [STALL_BACKEND_MEM] = ARMV8_AMU_PERFCTR_STALL_BACKEND_MEM
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC      drivers/iio/inkern.o
../drivers/devfreq/tensor_aio.c: In function 'create_perf_events':
../drivers/devfreq/tensor_aio.c:239:39: error: 'ARMV8_PMUV3_PERFCTR_STALL_BACKEND' undeclared (first use in this function)
  239 |                         attr.config = ARMV8_PMUV3_PERFCTR_STALL_BACKEND;
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>