google-modules: bms: Resolve multiple symbol definitions at link-time
Mark debug_printk_prlog and debug_no_logbuffer as extern, ensuring
they reference the existing global definition instead of creating
duplicate instances.

This resolves the following compilation errors:

/usr/lib/gcc/aarch64-linux-gnu/14.2.0/../../../../aarch64-linux-gnu/bin/ld: google-modules/bms/hl7132_gbms_pps.o (symbol from plugin): in function `hl7132_probe_pps':
(.text+0x0): multiple definition of `debug_no_logbuffer'; google-modules/bms/ln8411_gbms_pps.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/aarch64-linux-gnu/14.2.0/../../../../aarch64-linux-gnu/bin/ld: google-modules/bms/hl7132_gbms_pps.o (symbol from plugin): in function `hl7132_probe_pps':
(.text+0x0): multiple definition of `debug_printk_prlog'; google-modules/bms/ln8411_gbms_pps.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [../scripts/Makefile.vmlinux_o:63: vmlinux.o] Error 1
make[1]: *** [/home/0ctobot/Android/google/komodo/neutrino/neutrino_kernel_google_caimito/Makefile:1323: vmlinux_o] Error 2
make: *** [Makefile:266: __sub-make] Error 2

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>