google-modules: display: common: Define constants with explicit type casting
CHECK_DRM_CLOCK_DIVISIBLE_1000 expects CLOCK to be a compile-time
constant. Because the native definitions lack explicit type
casting, GCC fails to recognize it as such.

This resolves the following compilation error:

../google-modules/display/common/include/gs_drm/gs_display_mode.h:93:46: error: expression in static assertion is not constant
   93 |         struct {static_assert((CLOCK) % 1000 == 0, "drm clock not divisible by 1000."); }))
      |                               ~~~~~~~~~~~~~~~^~~~
../include/linux/build_bug.h:78:56: note: in definition of macro '__static_assert'
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
../google-modules/display/common/include/gs_drm/gs_display_mode.h:93:17: note: in expansion of macro 'static_assert'
   93 |         struct {static_assert((CLOCK) % 1000 == 0, "drm clock not divisible by 1000."); }))
      |                 ^~~~~~~~~~~~~
../google-modules/display/common/include/gs_drm/gs_display_mode.h:102:10: note: in expansion of macro 'CHECK_DRM_CLOCK_DIVISIBLE_1000'
  102 |         (CHECK_DRM_CLOCK_DIVISIBLE_1000(CLOCK) + (CLOCK / 1000))
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../google-modules/display/common/include/gs_drm/gs_display_mode.h:126:18: note: in expansion of macro 'CALC_DRM_CLOCK_K_HZ'
  126 |         .clock = CALC_DRM_CLOCK_K_HZ( \
      |                  ^~~~~~~~~~~~~~~~~~~
../google-modules/display/panels/caimito/panel-gs-tk4a.c:538:33: note: in expansion of macro 'DRM_MODE_TIMING'
  538 |                                 DRM_MODE_TIMING(60, HDISPLAY, HFP, HSA, HBP, VDISPLAY, VFP, VSA, VBP),
      |                                 ^~~~~~~~~~~~~~~
../google-modules/display/common/include/gs_drm/gs_display_mode.h:93:46: error: expression in static assertion is not constant
   93 |         struct {static_assert((CLOCK) % 1000 == 0, "drm clock not divisible by 1000."); }))
      |                               ~~~~~~~~~~~~~~~^~~~
../include/linux/build_bug.h:78:56: note: in definition of macro '__static_assert'
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
../google-modules/display/common/include/gs_drm/gs_display_mode.h:93:17: note: in expansion of macro 'static_assert'
   93 |         struct {static_assert((CLOCK) % 1000 == 0, "drm clock not divisible by 1000."); }))
      |                 ^~~~~~~~~~~~~
../google-modules/display/common/include/gs_drm/gs_display_mode.h:102:10: note: in expansion of macro 'CHECK_DRM_CLOCK_DIVISIBLE_1000'
  102 |         (CHECK_DRM_CLOCK_DIVISIBLE_1000(CLOCK) + (CLOCK / 1000))
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../google-modules/display/common/include/gs_drm/gs_display_mode.h:126:18: note: in expansion of macro 'CALC_DRM_CLOCK_K_HZ'
  126 |         .clock = CALC_DRM_CLOCK_K_HZ( \
      |                  ^~~~~~~~~~~~~~~~~~~
../google-modules/display/panels/caimito/panel-gs-tk4a.c:556:33: note: in expansion of macro 'DRM_MODE_TIMING'
  556 |                                 DRM_MODE_TIMING(120, HDISPLAY, HFP, HSA, HBP, VDISPLAY, VFP, VSA, VBP),
      |                                 ^~~~~~~~~~~~~~~
../google-modules/display/common/include/gs_drm/gs_display_mode.h:93:46: error: expression in static assertion is not constant
   93 |         struct {static_assert((CLOCK) % 1000 == 0, "drm clock not divisible by 1000."); }))
      |                               ~~~~~~~~~~~~~~~^~~~
../include/linux/build_bug.h:78:56: note: in definition of macro '__static_assert'
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
../google-modules/display/common/include/gs_drm/gs_display_mode.h:93:17: note: in expansion of macro 'static_assert'
   93 |         struct {static_assert((CLOCK) % 1000 == 0, "drm clock not divisible by 1000."); }))
      |                 ^~~~~~~~~~~~~
../google-modules/display/common/include/gs_drm/gs_display_mode.h:102:10: note: in expansion of macro 'CHECK_DRM_CLOCK_DIVISIBLE_1000'
  102 |         (CHECK_DRM_CLOCK_DIVISIBLE_1000(CLOCK) + (CLOCK / 1000))
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../google-modules/display/common/include/gs_drm/gs_display_mode.h:126:18: note: in expansion of macro 'CALC_DRM_CLOCK_K_HZ'
  126 |         .clock = CALC_DRM_CLOCK_K_HZ( \
      |                  ^~~~~~~~~~~~~~~~~~~
../google-modules/display/panels/caimito/panel-gs-tk4a.c:609:33: note: in expansion of macro 'DRM_MODE_TIMING'
  609 |                                 DRM_MODE_TIMING(30, HDISPLAY, HFP, HSA, HBP, VDISPLAY, VFP, VSA, VBP),
      |                                 ^~~~~~~~~~~~~~~

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>