google-modules: aoc: Fix additional GCC compile errors due to float assignments
Subsequent to 4600189 ("aoc: alsa: Fix GCC compile errors due to float assignments")

This resolves the following compilation errors:

In function 'aoc_compr_offload_playback_rate_set',
    inlined from 'aoc_compr_offload_playback_rate_ctl_set' at ../google-modules/aoc/alsa/aoc_alsa_ctl.c:1150:8:
../google-modules/aoc/alsa/aoc_alsa_hw.c:2605:19: error: '-mgeneral-regs-only' is incompatible with the use of floating-point types
 2605 |         cmd.speed = *(float *)(&tmp);
      |                   ^
../google-modules/aoc/alsa/aoc_alsa_hw.c:2607:19: error: '-mgeneral-regs-only' is incompatible with the use of floating-point types
 2607 |         cmd.pitch = *(float *)(&tmp);
      |                   ^
make[3]: *** [/tmp/ccE2dyGq.mk:278: /tmp/ccK9EgHN.ltrans92.ltrans.o] Error 1
make[3]: *** Waiting for unfinished jobs....
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>