google-devices: comet: display: Define constants with explicit type casting [2/2]
Subsequent to 838c792 ("google-modules: display: common: Define constants with explicit type casting [1/2]")

CHECK_DRM_CLOCK_DIVISIBLE_1000 expects CLOCK to be a compile-time
constant. Because the native definitions lack explicit type
casting, GCC fails to recognize it as such.

This resolves the following compilation error:

In file included from ../include/linux/container_of.h:5,
                 from ../include/linux/list.h:5,
                 from ../include/linux/wait.h:7,
                 from ../include/linux/wait_bit.h:8,
                 from ../include/linux/fs.h:6,
                 from ../include/linux/debugfs.h:15,
                 from ../google-devices/comet/display/panel-gs-ct3c.c:4:
../google-modules/../private/google-modules/display/common/include/gs_drm/gs_display_mode.h:93:46: error: expression in static assertion is not constant
   93 |         struct {static_assert((CLOCK) % 1000 == 0, "drm clock not divisible by 1000."); }))
      |                               ~~~~~~~~~~~~~~~^~~~
../include/linux/build_bug.h:78:56: note: in definition of macro '__static_assert'
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
../google-modules/../private/google-modules/display/common/include/gs_drm/gs_display_mode.h:93:17: note: in expansion of macro 'static_assert'
   93 |         struct {static_assert((CLOCK) % 1000 == 0, "drm clock not divisible by 1000."); }))
      |                 ^~~~~~~~~~~~~
../google-modules/../private/google-modules/display/common/include/gs_drm/gs_display_mode.h:102:10: note: in expansion of macro 'CHECK_DRM_CLOCK_DIVISIBLE_1000'
  102 |         (CHECK_DRM_CLOCK_DIVISIBLE_1000(CLOCK) + (CLOCK / 1000))
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../google-modules/../private/google-modules/display/common/include/gs_drm/gs_display_mode.h:126:18: note: in expansion of macro 'CALC_DRM_CLOCK_K_HZ'
  126 |         .clock = CALC_DRM_CLOCK_K_HZ( \
      |                  ^~~~~~~~~~~~~~~~~~~
../google-devices/comet/display/panel-gs-ct3c.c:673:33: note: in expansion of macro 'DRM_MODE_TIMING'
  673 |                                 DRM_MODE_TIMING(60, HDISPLAY, HFP, HSA, HBP,
      |                                 ^~~~~~~~~~~~~~~
../google-modules/../private/google-modules/display/common/include/gs_drm/gs_display_mode.h:93:46: error: expression in static assertion is not constant
   93 |         struct {static_assert((CLOCK) % 1000 == 0, "drm clock not divisible by 1000."); }))
      |                               ~~~~~~~~~~~~~~~^~~~
../include/linux/build_bug.h:78:56: note: in definition of macro '__static_assert'
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
../google-modules/../private/google-modules/display/common/include/gs_drm/gs_display_mode.h:93:17: note: in expansion of macro 'static_assert'
   93 |         struct {static_assert((CLOCK) % 1000 == 0, "drm clock not divisible by 1000."); }))
      |                 ^~~~~~~~~~~~~
../google-modules/../private/google-modules/display/common/include/gs_drm/gs_display_mode.h:102:10: note: in expansion of macro 'CHECK_DRM_CLOCK_DIVISIBLE_1000'
  102 |         (CHECK_DRM_CLOCK_DIVISIBLE_1000(CLOCK) + (CLOCK / 1000))
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../google-modules/../private/google-modules/display/common/include/gs_drm/gs_display_mode.h:126:18: note: in expansion of macro 'CALC_DRM_CLOCK_K_HZ'
  126 |         .clock = CALC_DRM_CLOCK_K_HZ( \
      |                  ^~~~~~~~~~~~~~~~~~~
../google-devices/comet/display/panel-gs-ct3c.c:691:33: note: in expansion of macro 'DRM_MODE_TIMING'
  691 |                                 DRM_MODE_TIMING(120, HDISPLAY, HFP, HSA, HBP,
      |                                 ^~~~~~~~~~~~~~~
../google-modules/../private/google-modules/display/common/include/gs_drm/gs_display_mode.h:93:46: error: expression in static assertion is not constant
   93 |         struct {static_assert((CLOCK) % 1000 == 0, "drm clock not divisible by 1000."); }))
      |                               ~~~~~~~~~~~~~~~^~~~
../include/linux/build_bug.h:78:56: note: in definition of macro '__static_assert'
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
../google-modules/../private/google-modules/display/common/include/gs_drm/gs_display_mode.h:93:17: note: in expansion of macro 'static_assert'
   93 |         struct {static_assert((CLOCK) % 1000 == 0, "drm clock not divisible by 1000."); }))
      |                 ^~~~~~~~~~~~~
../google-modules/../private/google-modules/display/common/include/gs_drm/gs_display_mode.h:102:10: note: in expansion of macro 'CHECK_DRM_CLOCK_DIVISIBLE_1000'
  102 |         (CHECK_DRM_CLOCK_DIVISIBLE_1000(CLOCK) + (CLOCK / 1000))
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../google-modules/../private/google-modules/display/common/include/gs_drm/gs_display_mode.h:126:18: note: in expansion of macro 'CALC_DRM_CLOCK_K_HZ'
  126 |         .clock = CALC_DRM_CLOCK_K_HZ( \
      |                  ^~~~~~~~~~~~~~~~~~~
../google-devices/comet/display/panel-gs-ct3c.c:746:33: note: in expansion of macro 'DRM_MODE_TIMING'
  746 |                                 DRM_MODE_TIMING(30, HDISPLAY, HFP, HSA, HBP,
      |                                 ^~~~~~~~~~~~~~~

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>