bcmdhd: Fix memset length for dhd->monitor_type in dhd_del_monitor_if()
GCC warns:
../google-modules/wlan/bcm4390/dhd_linux.c: In function 'dhd_del_monitor_if':
../google-modules/wlan/bcm4390/dhd_linux.c:5873:9: error: 'memset' used with length equal to number of elements without multiplication by element size [-Werror=memset-elt-size]
 5873 |         memset(dhd->monitor_type, 0, DHD_MAX_IFS);
      |         ^~~~~~

`monitor_type` is a uint array, and uint is not 1 byte, so the memset
length is incorrect. Fix it by using sizeof() on dhd->monitor_type itself.

Signed-off-by: Sultan Alsawaf <sultan@kerneltoast.com>
Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>

Conflicts:
	google-modules/wlan/bcm4390/dhd_linux.c