power: domain_governor: Pass cpu argument to cpu_latency_qos_limit()
Subsequent to 7ea8415 ("QoS: Enhance framework to support cpu/irq
specific QoS requests"), the function cpu_latency_qos_limit() now
requires a CPU ID argument.

This resolves the following compilation error:

../drivers/base/power/domain_governor.c: In function 'cpu_power_down_ok':
../drivers/base/power/domain_governor.c:368:29: error: too few arguments to function 'cpu_latency_qos_limit'
  368 |         global_constraint = cpu_latency_qos_limit();
      |                             ^~~~~~~~~~~~~~~~~~~~~
In file included from ../drivers/base/power/domain_governor.c:9:
../include/linux/pm_qos.h:166:5: note: declared here
  166 | s32 cpu_latency_qos_limit(int cpu);
      |     ^~~~~~~~~~~~~~~~~~~~~

[@0ctobot: Fixes 7ac1c9f ("pmdomain: governor: Consider CPU latency
tolerance from pm_domain_cpu_gov")]
Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>